<?php
echo '[{
		"airportFrom": "BGY",
		"airportTo": "FAO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "VLC",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "NOC",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "IBZ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CHQ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "FRA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TPS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "NUE",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PFO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "SKG",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CRV",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PRG",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "EDI",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BOJ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BLL",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "OMR",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "NYO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TER",
		"connectingAirport": "OPO",
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "OTP",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "SCQ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "SVQ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "WRO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "ACE",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CANARY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PSR",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BOD",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "NAP",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BDS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CPH",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CAG",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "AHO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "SUF",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "MAD",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "LDE",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "SXF",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TSR",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BRS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "FEZ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "ETHNIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "SDR",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CGN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PDV",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "AMM",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CTA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "NRN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "LPP",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "MAN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "MLA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "OPO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BCN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "EFL",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "INI",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "DUB",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "ZAZ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "HAM",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "EMA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BUD",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BVA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "ALC",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CIY",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CFU",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "LIS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "GSE",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "FUE",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CANARY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "LUX",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PMO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "LPA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CANARY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BRI",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "DOMESTIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "POZ",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BTS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "OSR",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "AGP",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "ORK",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TRF",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "VGO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "VNO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "ATH",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BRE",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "EIN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "STN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TFS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CANARY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "RHO",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "FAO",
		"connectingAirport": "OPO",
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TNG",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PMI",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "LEISURE"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TLV",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "WMI",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "RYG",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "GOT",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "RIX",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "CRL",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "PDL",
		"connectingAirport": "OPO",
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "TLL",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "VIT",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "VDA",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "GENERIC"
	}, {
		"airportFrom": "BGY",
		"airportTo": "GDN",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "BFS",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "KRK",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "CITY"
	}, {
		"airportFrom": "BGY",
		"airportTo": "RAK",
		"connectingAirport": null,
		"newRoute": false,
		"seasonalRoute": false,
		"operator": "RYANAIR",
		"group": "ETHNIC"
	}
]
';
?>
